# Generated by Django 4.2 on 2024-12-27 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='released_date',
            field=models.DateField(),
        ),
    ]
