# Generated by Django 4.2 on 2024-12-27 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_announcement_released_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enginecapacity',
            old_name='name',
            new_name='volume',
        ),
    ]
